"""empty message

Revision ID: 473cee9be54f
Revises: 
Create Date: 2020-04-30 22:25:19.565713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '473cee9be54f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=False),
    sa.Column('book_name', sa.String(length=15), nullable=False),
    sa.Column('author', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('library',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('library_name', sa.String(length=45), nullable=False),
    sa.Column('books_quantity', sa.String(length=45), nullable=False),
    sa.Column('visitors_quantity', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('library')
    op.drop_table('book')
    # ### end Alembic commands ###
